### ISSUE TITLE
[BUG] Available algorightms not displayed in UdL Portal

### ISSUE THREAD

**Issue by rogargon** [deltaDAO/portal-udl#32]
## Summary

Available algorithms for a dataset or datasets for an algorithm not being shown in the UdL Portal, while they appear in the main MVG.

## Steps to Reproduce

The available datasets for did:op:a6ad219784FA94F5888e135b524616e3BEb03B01 appear in the MVG portal:
https://portal.minimal-gaia-x.eu/asset/did:op:a6ad219784FA94F5888e135b524616e3BEb03B01

However, for the same algorithm, nothing is displayed if going through the UdL Portal:
https://udl.portal.minimal-gaia-x.eu/asset/did:op:a6ad219784FA94F5888e135b524616e3BEb03B01

**Comment by moritzkirstein** [comment]
This issue was related to a recent change on our metadata cache. It should be resolved now @rogargon.

**Comment by rogargon** [comment]
Thanks, this has partially solved the issue. Though now available algorithms appear in the dataset (and datasets in the algorithm) not all of them are shown.

In fact, for this algorithm, the enabled dataset is shown: https://udl.portal.minimal-gaia-x.eu/asset/did:op:8322cc19847DC556ed9FF9ddFf1C9bE5a3Ae34Cd

However, if you browse the dataset to start the algorithm, it is not shown there (though a different algorithm also enabled does): https://udl.portal.minimal-gaia-x.eu/asset/did:op:63c17BF06C57EA30eED1F8fEbD319B75dC89F59E

I've tried to refresh the page after disabling the cache or to re-edit the compute settings for the dataset but I've been unable to make the missing algorithm appear as a compute option.
